id: P004613
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 11:44:24.150902
source_metadata:
  id: bdr:W29662
  title: མཚན་ཉིད་རིག་པ་བློ་ཡི་ཉིན་བྱེད
  author: ''
  volumes:
    5e54809016074d22b8dfd666f2cddcde:
      image_group_id: I5549
      title: ''
      volume_number: 1
      total_pages: 42
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
