id: I835AA14E
legacy_id: P004613
ocr_import_info:
  bdrc_scan_id: W29662
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T04:36:14'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T14:15:00.099596+00:00'
last_modified: 2022-09-02 22:15:15.865534
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W29662
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW29662
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མཚན་ཉིད་རིག་པ་བློ་ཡི་ཉིན་བྱེད།
  author: མཁན་པོ་པདྨ་ཤེས་རབ།
statistics:
  ocr_word_mean_confidence_index: 0.9720210314964599
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I5549:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5549
      total_pages: 42
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I5549.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9720210314964599
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
